[package]
name = "agentic-rtb-framework-service"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "agentic-rtb-framework-service"
path = "src/main.rs"


[dependencies]
rustc-hash = "2.1.1"
tonic = "0.14.2"
tonic-prost = "0.14.2"
tonic-prost-build = "0.14.2"
prost = "0.14.1"
tokio ={ version = "1.43.0", features = ["rt-multi-thread", "macros"] }
tokio-stream = "0.1.17"
async-stream = "0.3.6"
futures = "0.3.31"
futures-util = "0.3.31"

[build-dependencies]
tonic-prost-build = "0.14.2"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true  # Enable link-time optimization.
codegen-units = 1  # Use a single codegen unit to reduce binary size.
